language: go
sudo: false

go:
  - "1.11.4"
  - "1.12"
  - "1.13"
  - "tip"

before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/mattn/goveralls

script:
  - go test -race ./...
  - goveralls -service=travis-ci

matrix:
  allow_failures:
    - go: tip

git:
  depth: 10

env:
  - GO111MODULE=on
